name: Run Python Tests on master branch (3.7)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unittests: TestMix
        run: python -m unittest tests.test_mix.TestMix
      - name: Run unittests: TestCollection
        run: python -m unittest tests.test_collection.TestCollection
      - name: Run unittests: TestBrainz
        run: python -m unittest tests.test_brainz.TestBrainz
