name: Run Python Tests on master branch (3.7)

on:
  push:
  pull_request:
    types: [opened, review_requested, synchronize, reopened, edited, ready_for_review]

jobs:
  unittest:
    runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unittests - TestMix
        run: |
          python -m unittest tests.test_mix.TestMix
      - name: Run unittests - TestConfig (first run)
        run: |
          python -m unittest tests.test_config.TestConfig
      - name: Run unittests - TestConfig (second run)
        run: |
          python -m unittest tests.test_config.TestConfig
      - name: Run unittests - TestCollection (first DiscoDOS run creates DB)
        run: |
          python -m unittest tests.test_collection.TestCollection
      - name: Run unittests - TestCollection (user is prompted for Discogs token)
        run: |
          python -m unittest tests.test_collection.TestCollection
      - name: Run unittests - TestBrainz
        run: |
          python -m unittest tests.test_brainz.TestBrainz
